version: '3.8'

services:
  namenode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-namenode
    hostname: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - ./hadoop-data/namenode:/hadoop/dfs/name
      - ./hadoop-data:/hadoop-data
    environment:
      - CLUSTER_NAME=docker-hadoop
    command: /etc/bootstrap.sh -d namenode

  datanode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-datanode
    hostname: datanode
    volumes:
      - ./hadoop-data/datanode:/hadoop/dfs/data
      - ./hadoop-data:/hadoop-data
    environment:
      - CLUSTER_NAME=docker-hadoop
    command: /etc/bootstrap.sh -d datanode

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./spark-data:/tmp/spark-data
      - ./spark-conf:/conf
      - /Users/nickphom/BigData:/Users/nickphom/BigData
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - "8081:8081"
      - "7500:7500"
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_CORES=7
      - SPARK_WORKER_MEMORY=24g
      - SPARK_WORKER_INSTANCES=1
      - SPARK_MASTER=spark://spark-master:7077
      #- SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./spark-data:/tmp/spark-data
      - ./spark-conf:/conf
      - /Users/nickphom/BigData:/Users/nickphom/BigData
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

